// USER ACTIONS
export const SIGN_IN = "SIGN_IN";
export const LOAD_TOKEN = "LOAD_TOKEN";
export const LOAD_ROL = "LOAD_ROL";

// MEASURE UNIT
export const LOAD_MEASURE = "LOAD_UNITS_OF_MEASURE";

// CATEGORY
export const LOAD_CATEGORIES = "LOAD_CATEGORIES";

// INGREDIENT
export const LOAD_INGREDIENTS = "LOAD_INGREDIENTS";

// PRODUCT
export const LOAD_PRODUCTS = "LOAD_PRODUCTS";

// ORDERS
export const LOAD_ORDERS = "LOAD_ORDERS";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const ADD_ORDER = "ADD_ORDER";

// BILLS
export const LOAD_BILLS = "LOAD_BILLS";

// USERS
export const LOAD_USERS = "LOAD_USERS";

// SECTION
export const LOAD_SECTION = "LOAD_SECTION";

// LOCATION
export const LOAD_LOCATION = "LOAD_LOCATION";

// ADDRESSES
export const LOAD_ADDRESSES = "LOAD_ADDRESSES";

// ROLS
export const LOAD_ROLS = "LOAD_ROLS";

// STATUSES
export const LOAD_STATUSES = "LOAD_STATUSES";

// MOVEMENTS
export const LOAD_MOVEMENTS = "LOAD_MOVEMENTS";